server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    # 表示将该微服务注册进Eureka Server
    register-with-eureka: true
    # 表示将从Eureka Server获取其他可用的微服务列表
    fetch-registry: true
    # Eureka Server的地址
    service-url:
#     defaultZone: http://localhost:7001/eureka
      # 集群版,将本微服务同时注册进多个eureka server,只需要将defaultZone改为多个地址,逗号隔开
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka