server:
  port: 80


eureka:
  client:
    register-with-eureka: false
#    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
# 设置Feign客户端超时时间(openfeign默认支持Ribbon)
ribbon:
  # ReadTimeout指建立连接所用时间,适用于网络连接正常的情况下,两端连接所用时间
  ReadTimeout: 5000
  # ConnectTimeout指建立连接之后从服务器读取到可用资源所用时间
  ConnectTimeout: 5000
# 配置Feign的日志功能
logging:
  level:
    # Feign日志以什么级别监控哪个接口
    com.zhang.springcloud.service.PaymentFeignService: debug

